import { NextResponse } from "next/server";
import { generateHseSuggestions } from "@/lib/ollama";

export const dynamic = "force-dynamic";
export const maxDuration = 60; // 60s max execution for Vercel serverless

/**
 * Endpoint: POST /api/suggest
 * Body: { hazard?: string, failed_barrier?: string, observation?: string }
 * Returns 3 actionable field tips generated by Ollama's safety model.
 */
export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const { hazard, failed_barrier, observation } = body;

    const suggestions = await generateHseSuggestions(hazard, failed_barrier, observation);

    return NextResponse.json({
      success: true,
      suggestions,
    });
  } catch (error: unknown) {
    const errorMessage =
      error instanceof Error ? error.message : "Failed to generate suggestions";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
